# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'globaleditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import editor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 591)
        MainWindow.setMinimumSize(QtCore.QSize(400, 422))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelFile = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelFile.setFont(font)
        self.labelFile.setToolTip("")
        self.labelFile.setToolTipDuration(-1)
        self.labelFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelFile.setScaledContents(False)
        self.labelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFile.setObjectName("labelFile")
        self.verticalLayout_4.addWidget(self.labelFile)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEditSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout_4.addWidget(self.lineEditSearch)
        
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.labelCurrentName = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrentName.setObjectName("labelCurrentName")
        font = QtGui.QFont()
        font.setBold(True)
        self.labelCurrentName.setFont(font)
        self.labelCurrentName.setAlignment(QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addWidget(self.labelCurrentName)
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.lineEditOld = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditOld.setObjectName("lineEditOld")
        self.lineEditOld.setReadOnly(True)
        self.verticalLayout_5.addWidget(self.lineEditOld)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEditNew = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNew.setObjectName("lineEditNew")
        self.lineEditNew.setMaxLength(2)
        self.lineEditNew.setReadOnly(True)
        self.verticalLayout_3.addWidget(self.lineEditNew)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveCopy = QtWidgets.QAction(MainWindow)
        self.actionSaveCopy.setObjectName("actionSaveCopy")
        self.actionWebsiteLink = QtWidgets.QAction(MainWindow)
        self.actionWebsiteLink.setObjectName("actionWebsiteLink")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveCopy)
        self.menuHelp.addAction(self.actionWebsiteLink)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelFile.setText(_translate("MainWindow", "No file open."))
        self.label_2.setText(_translate("MainWindow", "Search:"))
        self.label_3.setText(_translate("MainWindow", "Globals:"))
        self.labelCurrentName.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "Old value:"))
        self.label.setText(_translate("MainWindow", "New value:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaveCopy.setText(_translate("MainWindow", "Create backup copy"))
        self.actionWebsiteLink.setText(_translate("MainWindow", "Go to website..."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    e = editor.Editor()
    e.bindEvents(ui)
    e.populateList()
    
    MainWindow.setWindowTitle("Epic Mickey Save Global Editor")
    MainWindow.setWindowIcon(QtGui.QIcon("icon.png"))
    MainWindow.show()
    sys.exit(app.exec_())
